# Generated by Django 5.1.2 on 2024-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jshshir',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='series',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
